name: Continuous Integration
on:
  push:
    branches:
    - master

jobs:
  docker:
    name: Build Action Server Docker Image
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: donbale

    steps:
      - name: Checkout git repository 🕝
        uses: actions/checkout@v2

      - name: Login to DockerHub Registry 🔢
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ env.DOCKERHUB_USERNAME }} --password-stdin || true

      - name: Pull latest${{ matrix.image.tag_ext }} Docker image for caching
        run: docker pull donbale/smalltalk-demo:latest || true

      - name: Build latest${{ matrix.image.tag_ext }} Docker image
        run: docker build . --tag donbale/smalltalk-demo:latest --cache-from donbale/smalltalk-demo:latest

      - name: Push image with latest tag 📦
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: docker push donbale/smalltalk-demo:latest
